# Site settings
title:       Kiran
email:       kirans@berkeley.edu
author:      Kiran Suresh
description: "Kiran's Personal Website"
baseurl:     ""
url:         "https://kiransur.github.io"
date_format: "%b %-d, %Y"
header_pages:
 - reading.md
 - writing/index.html
 - projects.md

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
enable_mathjax: false
extended_fonts: true
enable_anchorjs: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    none
paginate:     4
paginate_path: "/writing/page:num/"
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
